apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql-db
  namespace: apps
spec:
  interval: 10m
  timeout: 15m
  releaseName: postgres-db
  chart:
    spec:
      chart: postgresql
      version: "18.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami-registry
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          database: database
          username: db_user
    primary:
      persistence:
        enabled: true
        size: 10Gi
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
