apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-charts
  namespace: flux-system
spec:
  interval: 2h
  type: oci
  url: oci://ghcr.io/reservoir-sandbox/helm-charts
