apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
  namespace: apps
spec:
  interval: 10m
  releaseName: backend
  chart:
    spec:
      chart: backend
      version: "0.1.4" # Will be automatically bumped by your CI pipeline
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: flux-system
  values:
    # Overriding only dynamic runtime values via GitOps
    image:
      repository: ghcr.io/reservoir-sandbox/backend
      tag: "5954b5723a33e18f762d7b36562bd338cb9f6353" # Example app commit SHA
      pullPolicy: IfNotPresent
