apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
  namespace: apps
spec:
  interval: 10m
  releaseName: backend
  chart:
    spec:
      chart: backend
      version: "0.1.13" # Will be automatically bumped by your CI pipeline
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: flux-system
  values:
    # Overriding only dynamic runtime values via GitOps
    image:
      repository: ghcr.io/reservoir-sandbox/backend
      tag: "4886a9f9532f30e6861f5c912d2913fe863d26ed" # Example app commit SHA
      pullPolicy: IfNotPresent
