apiVersion: v1
kind: Secret
metadata:
    name: worker-callback-secret
    namespace: apps
    labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/instance: backend
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:APW9GgdzsxqSM/dHWhm9/ZXN/qw+k/cRhxsGtVDE+U/Ky5LQKK99XXv6bYfcT47mQyEDeutMUyzXmDVd3pHzNA==,iv:SUIePmKsVM1y1gwMZHtZx1I2JXrG1Sgcb/ZO7rNtnN0=,tag:qcXHBUTowtwIlaWS1ITp0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRGNJL3FwOUE0Zkgrcno5
            S0ticHdoNkFsVVdPZlhxTTdIUGNUdW9YK0FvCjQzV1JEOHZJd1ZvY2ZuSDRFTTZY
            dWc3eU9FTkdCVFUxODFxY09HREdoUnMKLS0tIEpZanRsdy84K3pZQzFIVHBLYStQ
            bDBNcVZuY09EWUU5cFhXbU9sU2gya1kKtCIF6KMtAL+qdhoObMPyQAxjaJjcwYLc
            eNHKqPX2W81J7mfFfATzReeOP6tjW+xTIwfOAVVxPs/W5LFXQPJtHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y36s4l5rgmvtpkpnu7zrqxyux3p43dv2j40na29cgr73ffsw8drqp8z87v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:34:58Z"
    mac: ENC[AES256_GCM,data:NDTeKH18U1sSZHqqdv8MAn15oMPLh0bHK30+4NboW9fDKjEuadcakmaBjQhrRcm8CCbD5OeOdNDhZdPgM1B+PwQ2fUJh4T2gUzoeOPvQ+uoFzGHHUB3+MIsGW6Edth75YbGdr8WgR5rsPFdgLpmq5QY83yalQdn7WciHhDq2MO8=,iv:lxRqrR2ePXnOZSSLMYPmXPZTIelGbxU3MeBn1tQqZ/k=,tag:9xqg/JIXsUbNiVIQSUdQSg==,type:str]
    version: 3.13.1
