apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-job-launcher
  namespace: jobs
rules:
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-job-launcher
  namespace: jobs
subjects:
  - kind: ServiceAccount
    name: backend
    namespace: apps
roleRef:
  kind: Role
  name: backend-job-launcher
  apiGroup: rbac.authorization.k8s.io
