apiVersion: v1
kind: Secret
metadata:
    name: worker-callback-secret
    namespace: jobs
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:vxRAaEg1n1UMQaapww70kHBoIIRdPalsRYziLyvRYS4Lku0VF6Jn8e4CSiObTpcDa1Df3DdgtngGDhuq5VK1IQ==,iv:+AY/GwoO8m7oI/d9qGMJAk06v8eCmt3nLajBHMDjMTY=,tag:rOWyLggUir0CmrQgXVtqPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bHBrcVBwSjhRUHY4cnZO
            OU8vV0cwelZ4OE9nM0pxVzdpNzVMZGVlSkJRCmx1QWM4TWdYdis3TEFRWjNuRWhj
            YnovTUNSZm9hN1FCMlUybUdKREVNVzgKLS0tIGRNS2hPd0dPV2ZDekRRci9penVG
            L1RrY0ZMWnRSNStYdWlFQmFBVTFySlUKuZB6hgUAu/d9cCQ67aHM5/qC3v9OohV8
            RCs2ulZ48LVw/WtQO3tlRj2GlOcK2b5MOfesuo12ZkuBLIhSTpwvBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y36s4l5rgmvtpkpnu7zrqxyux3p43dv2j40na29cgr73ffsw8drqp8z87v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:34:44Z"
    mac: ENC[AES256_GCM,data:r5Q+qkCm+6DlWl0+xDjaO1d9irzwLMRTtDc8+XIr189pZ4P1QUIamKZSmVbQ+xv8+Pjs7edS+CdhDvoLRwF67Ujocw+jS2YNMQfJ8s8ZhCwZRXrXmvrX/ZB8JVt5qHK6PArLVA4mZWXP64l4waCQBLTbmg4ZUCO36Exi9iM4Xvs=,iv:CPmUVl4QvcF3k28HCzgewk2RPtJNPRz+V+Jfz+PLeOQ=,tag:MMj9v0qnkTTv6EXkbVii8A==,type:str]
    version: 3.13.1
