apiVersion: v1
kind: Secret
metadata:
    name: garage-backend-key
    namespace: infrastructure
type: Opaque
stringData:
    keyId: ENC[AES256_GCM,data:lNKEBFao6Q0YXJIaQSbFRC7NfzdQayFRSCI=,iv:v+FkLCQ5DGPDD7X9Y3Ayfr601kF6PA+xTXk1aatmp6M=,tag:PzWXTQU5SiamTrrvLQ+wjQ==,type:str]
    secretKey: ENC[AES256_GCM,data:XSUPcvLiiBGWXV6YX6LkGCqT88tgC5zWjstbNMkRDwvVRmfTPmX69pNx6mTjOBAx2Gzmo/zmmrX27CX5uVcXfA==,iv:hTWmBRRZiZBvVNQo1vzUFa2QUPTFZVz/EXdK/aTkm5w=,tag:vxUfMpstwohJ8Q074AFWew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWHg1Y0ttcFhwOWxnd0Nj
            UGZsQVhCUHFCeGZMYWtLQjVmN0t0REdkSEZjClFQMnZFMGNENjh3NklVSEFjb1Bk
            b3FkTjRVMXI4S29JTXhKeHpjOXdVd1UKLS0tIFVZTTJwK2R2c3o1MnlyU3RKcE4z
            REo1WGFQWE0yVlhhSWlKVjRDYXd2bWcK6eimjjiMXPjpAd2kf59hgEfxoX5YrhFt
            OMrDa8TexYKPguVlsbeiBSecn6GyuglX/wtKbM4Eo6XS37+YXZTeUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y36s4l5rgmvtpkpnu7zrqxyux3p43dv2j40na29cgr73ffsw8drqp8z87v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T14:17:04Z"
    mac: ENC[AES256_GCM,data:72KHAsan1JASZSCrAzFiaBhFCW1V0Y34MnpRYP2x6TLqJEWM8gWYhxrHtn8NvBsrKk9SiubWa6GpLTM8FkuZlRdamMVcuwpriZ/hywGbtqDPfB/kahLi44HozXSbVaHKDmkm1VOaVOBUB8gBupB4p5WHU8kFJIr8jk9r85CtFIc=,iv:O+i7G0T+1nO0Tt4budNZYXN3xD+YU5gdgXUghf3+OJY=,tag:fl5cs2Mxk4AvDyTE6PSSvw==,type:str]
    version: 3.13.1
