apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - security/namespaces.yaml
  - sources/bitnami-registry.yaml
  - sources/datahub-registry.yaml
  - sources/helm-charts.yaml
  - sources/kubernetes-nginx-repo.yaml
  - storage/local-path-storageclass.yaml
  - ingress/nginx-release.yaml
  - s3/garage-backend-key-secret.yaml
  - s3/garage-s3-release.yaml
