apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database/postgres-release.yaml
  - cache/redis-release.yaml
  - frontend/frontend-release.yaml
  - backend/backend-release.yaml
