apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database/postgres-release.yaml
  - cache/redis-release.yaml
  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - frontend/networkpolicy.yaml
  - backend/configmap.yaml
  - backend/serviceaccount.yaml
  - backend/worker-callback-secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml
  - backend/networkpolicy.yaml
